remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
title: "Hanno's personal blog"
author: Hanno Küpers
github_username: nanohanno
linkedin_username: hanno-kupers

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap #
